apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - image: "mjgacr.azurecr.io/webapi"
          imagePullPolicy: Always
          name: webapi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webapi
