apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi
  storageClassName: default
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: volume
      initContainers:
        - command:
            - sh
            - '-c'
            - until grep -qs "/usr/share/nginx/html " /proc/mounts; do sleep 1; done; echo Hello, World! > /usr/share/nginx/html/index.html
          image: busybox
          name: init-nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azuredisk
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - port: 80
  selector:
    app: nginx
  type: LoadBalancer