apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azuredisk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1024Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-dynamicdiskprobe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - image: "mjgacr.azurecr.io/webapi"
          imagePullPolicy: Always
          name: webapi
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: "/mnt/azure"
            name: volume
          readinessProbe:
            exec:
              command:
              - cat
              - /mnt/azure/test.txt
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azuredisk
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webapi
---