apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-staticdisk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - image: "mjgacr.azurecr.io/webapi"
          imagePullPolicy: Always
          name: webapi
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: "/mnt/azure"
            name: volume
      volumes:
        - name: volume
          azureDisk:
            kind: Managed
            diskName: aksstatic
            diskURI: /subscriptions/ae11b860-a23e-44ad-b37d-16053ab03c62/resourceGroups/MC_mjgaks-rg_mjgaks_centralus/providers/Microsoft.Compute/disks/aksstatic
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webapi
---